const fs = require('fs')

var conselhos = [
    "Mantenha a calma em momentos de adversidade.",
    "Pratique a gratidão diariamente.",
    "Reserve um tempo para cuidar de si mesmo.",
    "Esteja aberto a novas oportunidades.",
    "Aprenda com seus erros e fracassos.",
    "Pense positivamente, mesmo diante dos desafios.",
    "Seja paciente com você mesmo e com os outros.",
    "Valorize os relacionamentos pessoais.",
    "Estabeleça metas claras e alcançáveis.",
    "Leve uma vida equilibrada entre trabalho e lazer.",
    "Aprenda a dizer 'não' quando necessário.",
    "Mantenha-se ativo fisicamente todos os dias.",
    "Pratique a empatia ao lidar com os outros.",
    "Cultive hobbies que tragam alegria e relaxamento.",
    "Seja proativo na resolução de problemas.",
    "Mantenha uma mente aberta para diferentes pontos de vista.",
    "Economize dinheiro para emergências futuras.",
    "Aprenda a perdoar e deixar ir ressentimentos.",
    "Invista em seu desenvolvimento pessoal constantemente.",
    "Dedique tempo para aprender coisas novas.",
    "Mantenha-se hidratado bebendo água suficiente.",
    "Evite procrastinar tarefas importantes.",
    "Seja gentil com os animais e cuide deles.",
    "Aprecie as pequenas coisas da vida.",
    "Pratique a honestidade em todas as situações.",
    "Mantenha contato com amigos e familiares.",
    "Descubra maneiras saudáveis de lidar com o estresse.",
    "Tire um tempo para meditar e relaxar a mente.",
    "Coma uma dieta balanceada e nutritiva.",
    "Defina limites saudáveis nos relacionamentos.",
    "Aprenda a delegar tarefas quando necessário.",
    "Aceite as mudanças como oportunidades de crescimento.",
    "Seja pontual e respeite o tempo dos outros.",
    "Cultive a paciência em situações difíceis.",
    "Mantenha seu espaço pessoal organizado.",
    "Acredite em suas habilidades e capacidades.",
    "Evite se comparar aos outros; cada jornada é única.",
    "Seja um ouvinte atento quando alguém precisar.",
    "Pratique a moderação em todas as áreas da vida.",
    "Demonstre apreço e reconhecimento pelas pessoas.",
    "Respire profundamente quando sentir-se sobrecarregado.",
    "Lidere pelo exemplo e inspire os outros.",
    "Aproveite o poder do 'não sei', e esteja disposto a aprender.",
    "Aprenda a lidar com a rejeição de maneira saudável.",
    "Crie uma rotina que promova equilíbrio e bem-estar.",
    "Comunique-se de forma clara e respeitosa.",
    "Pratique a autocompaixão nas dificuldades.",
    "Dê passos pequenos, mas consistentes, em direção aos objetivos.",
    "Aprenda a lidar com críticas de maneira construtiva.",
    "Celebre suas conquistas, não importa o quão pequenas sejam.",
    "Crie memórias através de experiências, não apenas bens materiais.",
    "Cultive a humildade e admita quando estiver errado.",
    "Mantenha-se curioso e aberto a explorar o desconhecido.",
    "Aprenda a dizer 'desculpe' quando necessário.",
    "Compartilhe seu conhecimento com os outros.",
    "Aceite ajuda quando estiver sobrecarregado.",
    "Mantenha um círculo social diversificado.",
    "Crie metas realistas e mensuráveis.",
    "Pratique a resiliência diante das adversidades.",
    "Dedique tempo para se conectar com a natureza.",
    "Seja gentil consigo mesmo em momentos de falha.",
    "Desenvolva a capacidade de resolver problemas de forma criativa.",
    "Invista em relacionamentos saudáveis e significativos.",
    "Aprenda a lidar com a incerteza de maneira tranquila.",
    "Evite se preocupar com coisas fora do seu controle.",
    "Priorize o sono adequado para a saúde geral.",
    "Desligue-se das telas e reserve tempo para o mundo real.",
    "Seja generoso com seu tempo e recursos.",
    "Aprenda a dizer 'obrigado' sinceramente.",
    "Pratique a autoaceitação e ame quem você é.",
    "Desenvolva sua inteligência emocional para lidar melhor com emoções.",
    "Aprenda a estabelecer limites saudáveis no trabalho.",
    "Promova a igualdade e a justiça em todas as áreas.",
    "Mantenha-se informado sobre questões globais.",
    "Crie uma atmosfera de cooperação, não de competição.",
    "Inspire-se em modelos positivos e motivadores.",
    "Encontre maneiras de contribuir para sua comunidade.",
    "Aprenda a se desculpar quando machucar alguém.",
    "Evite julgar os outros; ninguém é perfeito.",
    "Mantenha-se aberto a novas perspectivas.",
    "Dê atenção plena às atividades do dia a dia.",
    "Lidere sua vida com base em valores sólidos.",
    "Aprenda a soltar o passado e abraçar o presente.",
    "Desenvolva sua autoconfiança ao longo do tempo.",
    "Cultive a atitude de aprendizado contínuo.",
    "Evite a procrastinação e tome medidas agora.",
    "Mantenha um equilíbrio entre trabalho, descanso e lazer.",
    "Aprenda a se defender de maneira respeitosa.",
    "Pratique a autenticidade e seja verdadeiro consigo mesmo.",
    "Invista tempo em atividades criativas que você ama.",
    "Seja flexível e adaptável às mudanças.",
    "Dê importância à sua saúde mental tanto quanto à física.",
    "Aprenda a administrar seu tempo de forma eficaz.",
    "Desenvolva habilidades de comunicação interpessoal.",
    "Crie um ambiente que promova paz e tranquilidade.",
    "Aprenda a expressar seus sentimentos de maneira saudável.",
    "Evite comparar sua jornada com a dos outros.",
    "Mantenha a humildade mesmo em face do sucesso."]

cantadas = [
    "Você é um sol? Porque ilumina o meu dia.",
    "Se beleza fosse tempo, você seria a eternidade.",
    "Acredita em amor à primeira vista ou devo passar por aqui novamente?",
    "Você não é Wi-Fi, mas estou sentindo uma conexão.",
    "Se você fosse um ladrão, roubaria apenas sorrisos.",
    "Posso te seguir? Porque minhas mãos estão frias e eu adoraria segurar as suas.",
    "Você é tão doce que está me dando cárie.",
    "Acredita em destino? Porque acabei de encontrar o meu.",
    "Você é uma lanterna? Porque ilumina a minha vida.",
    "Eu não sou fotógrafo, mas posso te imaginar juntos.",
    "Você não é o Google, mas tem tudo que tenho procurado.",
    "Você é feito de cobre e telúrio? Porque você é Cu-Te.",
    "Se você fosse uma fruta, você seria uma uva: pequena, roxa e sem caroço.",
    "Você é o açúcar? Porque está adoçando o meu dia.",
    "Se beleza fosse tempo, você seria a eternidade.",
    "Eu não sou astronauta, mas posso te levar às estrelas.",
    "Você acredita em amor à primeira vista ou devo passar por aqui novamente?",
    "Posso te tirar uma foto? Quero mostrar ao Papai Noel o que quero de presente.",
    "Seu nome é Google? Porque você tem tudo o que estou procurando.",
    "Seu pai é um padeiro? Porque você é uma gostosura.",
    "Você é fã de música? Porque nossa sintonia é perfeita.",
    "Eu não sou casas Bahia, mas minha dedicação é total a você.",
    "Você é o ovo que faltava na minha marmita.",
    "Você não é Nescau, mas é nescessário.",
    "Você não é tinta, mas coloriu meu mundo.",
    "Eu não sou Neymar, mas me apaixonei no primeiro dribble.",
    "Você não é juíza, mas tem um lugar cativo no meu coração.",
    "Não sou Fred, mas vou te dar uma caneta.",
    "A lua é linda, mas não tanto quanto você.",
    "Você é o que faltava na minha vida, um pedaço de pizza.",
    "Você é o arroz do meu feijão, a batata do meu escondidinho.",
    "Se você fosse uma fruta, seria um morango, porque é uma delícia.",
    "Eu não sou o Batman, mas estou sempre pronto para salvar você.",
    "Você é a senha do meu Wi-Fi, sempre na minha mente.",
    "Posso te chamar de Google? Porque você tem tudo o que procuro.",
    "Você não é religião, mas quando te vejo, digo: Meu Deus!",
    "Posso saber o que você está tomando para ser tão gostosa assim?",
    "Se você fosse um sanduíche, seria um X-princesa.",
    "Não sou jogador de futebol, mas estou louco para fazer um gol no seu coração.",
    "Você é a água da minha torneira, não posso viver sem você.",
    "Eu não sou o Sílvio Santos, mas você topa ganhar um milhão?",
    "Você é a lua de uma noite de verão, ilumina tudo ao redor.",
    "Não sou a Tim, mas minha vida inteira é estar ao seu lado.",
    "Você não é concurso público, mas passei a te admirar depois da primeira vista.",
    "Se você fosse um hambúrguer, seria um X-princesa.",
    "Eu não sou o Itaú, mas fui feito para você.",
    "Você não é código de barras, mas quero te scanear todinha.",
    "Você não é o Google, mas tem tudo o que procuro.",
    "Se você fosse um Pokémon, seria um 'Amoritite'.",
    "Não sou o Neymar, mas caí de amores por você.",
    "Posso te fazer uma pergunta? Você acredita em amor à primeira vista?",
    "Você é o sol do meu dia e a lua da minha noite.",
    "Você é a chave do meu coração. Posso te levar pra casa?",
    "Você é a senha do meu Wi-Fi. Sem você, nada funciona.",
    "Posso não ser o Shrek, mas sou ogro pra caramba.",
    "Você é o açaí do meu pote.",
    "Se você fosse um emoticon, seria o emoji de coração.",
    "Você não é açaí, mas mexeu com o meu coração.",
    "Você é feito de chá? Porque você está quente e me acalma.",
    "Você é a maionese do meu X-burger.",
    "Você não é palhaço, mas me faz rir à toa.",
    "Você é o ovo da minha marmita. Sem você, não tem graça.",
    "Você é a metade do meu sanduíche.",
    "Você não é o Bob Esponja, mas vive no meu coração.",
    "Você é a batata do meu escondidinho.",
    "Você é a letra da minha música.",
    "Você é a canela do meu café.",
    "Você é o Mickey da minha Disney.",
    "Você é a Nutella do meu pão.",
    "Você é o doce do meu brigadeiro.",
    "Você é a goiabada do meu Romeu e Julieta.",
    "Você é o queijo do meu misto quente.",
    "Você é o biscoito do meu café.",
    "Você é o ketchup do meu hambúrguer.",
    "Você é o sal do meu churrasco.",
    "Você é o tempero da minha vida.",
    "Você é a luz do meu caminho.",
    "Você é o cheddar da minha batata.",
    "Você é o creme do meu sonho.",
    "Você é o chocolate quente do meu inverno.",
    "Você é a lua do meu céu.",
    "Você é o sonho da minha realidade.",
    "Você é a pipoca do meu cinema.",
    "Você é o pote de ouro do meu arco-íris.",
    "Você é a maçã do meu jardim.",
    "Você é a água da minha sede.",
    "Você é a melodia da minha canção.",
    "Você é o açúcar do meu café.",
    "Você é a lua do meu universo."]
    
module.exports = {
  conselhos,
  cantadas
}
  
