const fs = require('fs')

var conselhos = [
    "Mantenha a calma em momentos de adversidade.",
    "Pratique a gratidão diariamente.",
    "Reserve um tempo para cuidar de si mesmo.",
    "Esteja aberto a novas oportunidades.",
    "Aprenda com seus erros e fracassos.",
    "Pense positivamente, mesmo diante dos desafios.",
    "Seja paciente com você mesmo e com os outros.",
    "Valorize os relacionamentos pessoais.",
    "Estabeleça metas claras e alcançáveis.",
    "Leve uma vida equilibrada entre trabalho e lazer.",
    "Aprenda a dizer 'não' quando necessário.",
    "Mantenha-se ativo fisicamente todos os dias.",
    "Pratique a empatia ao lidar com os outros.",
    "Cultive hobbies que tragam alegria e relaxamento.",
    "Seja proativo na resolução de problemas.",
    "Mantenha uma mente aberta para diferentes pontos de vista.",
    "Economize dinheiro para emergências futuras.",
    "Aprenda a perdoar e deixar ir ressentimentos.",
    "Invista em seu desenvolvimento pessoal constantemente.",
    "Dedique tempo para aprender coisas novas.",
    "Mantenha-se hidratado bebendo água suficiente.",
    "Evite procrastinar tarefas importantes.",
    "Seja gentil com os animais e cuide deles.",
    "Aprecie as pequenas coisas da vida.",
    "Pratique a honestidade em todas as situações.",
    "Mantenha contato com amigos e familiares.",
    "Descubra maneiras saudáveis de lidar com o estresse.",
    "Tire um tempo para meditar e relaxar a mente.",
    "Coma uma dieta balanceada e nutritiva.",
    "Defina limites saudáveis nos relacionamentos.",
    "Aprenda a delegar tarefas quando necessário.",
    "Aceite as mudanças como oportunidades de crescimento.",
    "Seja pontual e respeite o tempo dos outros.",
    "Cultive a paciência em situações difíceis.",
    "Mantenha seu espaço pessoal organizado.",
    "Acredite em suas habilidades e capacidades.",
    "Evite se comparar aos outros; cada jornada é única.",
    "Seja um ouvinte atento quando alguém precisar.",
    "Pratique a moderação em todas as áreas da vida.",
    "Demonstre apreço e reconhecimento pelas pessoas.",
    "Respire profundamente quando sentir-se sobrecarregado.",
    "Lidere pelo exemplo e inspire os outros.",
    "Aproveite o poder do 'não sei', e esteja disposto a aprender.",
    "Aprenda a lidar com a rejeição de maneira saudável.",
    "Crie uma rotina que promova equilíbrio e bem-estar.",
    "Comunique-se de forma clara e respeitosa.",
    "Pratique a autocompaixão nas dificuldades.",
    "Dê passos pequenos, mas consistentes, em direção aos objetivos.",
    "Aprenda a lidar com críticas de maneira construtiva.",
    "Celebre suas conquistas, não importa o quão pequenas sejam.",
    "Crie memórias através de experiências, não apenas bens materiais.",
    "Cultive a humildade e admita quando estiver errado.",
    "Mantenha-se curioso e aberto a explorar o desconhecido.",
    "Aprenda a dizer 'desculpe' quando necessário.",
    "Compartilhe seu conhecimento com os outros.",
    "Aceite ajuda quando estiver sobrecarregado.",
    "Mantenha um círculo social diversificado.",
    "Crie metas realistas e mensuráveis.",
    "Pratique a resiliência diante das adversidades.",
    "Dedique tempo para se conectar com a natureza.",
    "Seja gentil consigo mesmo em momentos de falha.",
    "Desenvolva a capacidade de resolver problemas de forma criativa.",
    "Invista em relacionamentos saudáveis e significativos.",
    "Aprenda a lidar com a incerteza de maneira tranquila.",
    "Evite se preocupar com coisas fora do seu controle.",
    "Priorize o sono adequado para a saúde geral.",
    "Desligue-se das telas e reserve tempo para o mundo real.",
    "Seja generoso com seu tempo e recursos.",
    "Aprenda a dizer 'obrigado' sinceramente.",
    "Pratique a autoaceitação e ame quem você é.",
    "Desenvolva sua inteligência emocional para lidar melhor com emoções.",
    "Aprenda a estabelecer limites saudáveis no trabalho.",
    "Promova a igualdade e a justiça em todas as áreas.",
    "Mantenha-se informado sobre questões globais.",
    "Crie uma atmosfera de cooperação, não de competição.",
    "Inspire-se em modelos positivos e motivadores.",
    "Encontre maneiras de contribuir para sua comunidade.",
    "Aprenda a se desculpar quando machucar alguém.",
    "Evite julgar os outros; ninguém é perfeito.",
    "Mantenha-se aberto a novas perspectivas.",
    "Dê atenção plena às atividades do dia a dia.",
    "Lidere sua vida com base em valores sólidos.",
    "Aprenda a soltar o passado e abraçar o presente.",
    "Desenvolva sua autoconfiança ao longo do tempo.",
    "Cultive a atitude de aprendizado contínuo.",
    "Evite a procrastinação e tome medidas agora.",
    "Mantenha um equilíbrio entre trabalho, descanso e lazer.",
    "Aprenda a se defender de maneira respeitosa.",
    "Pratique a autenticidade e seja verdadeiro consigo mesmo.",
    "Invista tempo em atividades criativas que você ama.",
    "Seja flexível e adaptável às mudanças.",
    "Dê importância à sua saúde mental tanto quanto à física.",
    "Aprenda a administrar seu tempo de forma eficaz.",
    "Desenvolva habilidades de comunicação interpessoal.",
    "Crie um ambiente que promova paz e tranquilidade.",
    "Aprenda a expressar seus sentimentos de maneira saudável.",
    "Evite comparar sua jornada com a dos outros.",
    "Mantenha a humildade mesmo em face do sucesso."]

module.exports = {
  conselhos
}
  
